name: Voodoo Studio
favicon: null
layout_spectrum: 0.04636
typography_spectrum: 0.10803
title: Voodoo Studio ~ opnamestudio ~ live sound
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262628'
    - '#e8dede'
    - '#505052'
    - '#c7bebf'
    - '#6f6d70'
  brandStrength: 0.25
  lightness: 0.9297872
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
