name: Voodoo Studio
favicon: null
layout_spectrum: 0.8357888541650027
typography_spectrum: 0.3572863023728132
title: opnamestudio ~ live sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262628'
    - '#e8dede'
    - '#505052'
    - '#c7bebf'
    - '#6f6d70'
  brandStrength: 0.8935506062116474
  lightness: 0.7456042165867984
  saturation: 0.41904711490496993
  rhythmicContrast: 0.5
purpose: []
