typography_spectrum: 0.0984
color:
  brandColors:
    - '#010310'
    - '#ab7b65'
    - '#3a1b23'
    - '#6b3938'
    - '#ffffe3'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.04636
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jeroen Marien
  email: info@voodoostudio.be
  url: voodoostudio.be
name: Voodoo Studio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: facebook
    url: >-
      https://www.facebook.com/Voodoo-Studio-opnamestudio-live-sound-115917756538/
    type: external
  - name: Gearlist
    id: f62c10bf-6f8a-45c6-bf01-7b397c036709
    type: content
  - name: contact
    id: 7b6cdfca-f059-4c5f-b997-e7cddb44e512
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: ~ opnamestudio ~ live sound ~
purpose: []
